#!/bin/sh
set -e
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
BASEPATH=$(dirname "$SCRIPTPATH")
DATAPATH="$BASEPATH/data"

if [ -z "${USER_TOKEN}" ]; then
    echo "No user token provided" >&2
    exit 1
fi

if [ ! $# -eq 2 ]; then
    echo "usage: add-to-user ORGA MY_TOKEN" >&2
    exit 1
fi

ORGA="$1"
OTHER_TOKEN="$2"
"$SCRIPTPATH/check-permissions" "$ORGA"
[ ! -d "$DATAPATH/ids/$OTHER_TOKEN" ] && mkdir -p "$DATAPATH/ids/$OTHER_TOKEN"
ln -s "../../repos/$ORGA" "$DATAPATH/ids/$OTHER_TOKEN/$ORGA"
echo "Orga $ORGANIZATION is now owned by $OTHER_TOKEN"
exit 0
