#!/bin/sh

set -e

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
BASEPATH=$(dirname "$SCRIPTPATH")
REPOPATH="$BASEPATH/repos"

ORGA=$(echo "$1"|cut -d'/' -f2)
REPO=$(echo "$1"|cut -d'/' -f3-)
REPO=$(basename -s .git "$REPO")

GIT_NAMESPACE="$ORGA" git-upload-pack --strict "$REPOPATH/$ORGA/$REPO.git"
