#!/bin/sh
printf '%s' '#!/bin/sh
#########################################################################
# This script will setup a git-server on your machine if copy pasted and
# executed in an empty directory.
#########################################################################

set -e 
GIT_URL=https://github.com/kalkin

if [ ! -d .git/ ]; then
    git init .
fi

AUTHOR="Marvin the Paranoid Android <marvin@example.com>" 
DATA_DIR="data"
REPOS_DIR="$DATA_DIR/repos"
TOKENS_DIR="$DATA_DIR/ids"
ORGS_DIR="$DATA_DIR/orgs"
export GIT_ALLOW_PROTOCOL="ext:ssh:https"

commit() { git commit --quiet --signoff --author "$AUTHOR" --message "$1"; }

submodule_add() { git submodule add -b master "ext::git --namespace=admin %s $1" "$2"; }

migrate() {
    TMP_DIR="tmp"
    mkdir -p "$TMP_DIR"
    echo "Checking out $1"
    git clone --quiet --bare "$GIT_URL/$1" "$TMP_DIR/$1"
    src_repo="$TMP_DIR/$1"
    repo_name=$(git --git-dir="$src_repo" rev-list --max-parents=0 HEAD)
    dst="$REPOS_DIR/$repo_name.git"
    git init --bare "$dst" --quiet
    git --git-dir="$src_repo" remote add _migrate "ext::git --namespace=admin %s $dst"
    git --git-dir="$src_repo" --namespace=admin push _migrate --all --quiet
    git --git-dir="$dst" remote add origin "$GIT_URL/$1"
    echo "$dst"
    submodule_add "$dst" "$2"
    ln -s  "../../repos/$repo_name.git" "$ORGS_DIR/admin/$1"
    rm -rf "$TMP_DIR"
}

create_dir() {
    mkdir -p "$1"
    touch "$1/.keep"
    echo "$1/*" >> .gitignore
    git add "$1/.keep" ".gitignore" -f
    commit "Create $1"
}

create_dir $TOKENS_DIR
create_dir $REPOS_DIR
create_dir $ORGS_DIR
mkdir "$ORGS_DIR/admin"

migrate "git-server-tools" "bin"
migrate thinssh "thinssh"

echo "1" > .schema_version
git add .schema_version
commit "Set schema_version to 1"

echo "#!/bin/sh
exec thinssh/bin/thinssh.$(uname -m)" > git-server
chmod +x git-server
git add git-server
commit "Add thinssh/"
if [ ! -f host_key ]; then
    ssh-keygen -t ed25519 -f host_key -N ""
fi
git add host_key
if [ -f host_key.pub ]; then
    git add host_key.pub
fi
commit "Add ssh key"
rm install

#############################################################################
# The above script will setup a git-server on your machine. 
#
# 0. Create an new directory for your server data
# 1. Copy paste this output in an the new directory in a file called "install"
# 2. Make the file "install" executable and execute it
# 3. After execution just start "./git-server"
# 
##############################################################################
# vim: tw=0
'
