#!/bin/sh
printf '%s' '#!/bin/sh
#########################################################################
# This script will setup a git-server on your machine if copy pasted and
# executed in an empty directory.
#########################################################################

set -e 
GIT_URL=https://github.com/kalkin

if [ ! -d .git/ ]; then
    git init .
fi

AUTHOR="Marvin the Paranoid Android <marvin@example.com>" 
DATA_DIR="data"
REPOS_DIR="repos"
TOKENS_DIR="ids"
ORGS_DIR="orgs"
export GIT_ALLOW_PROTOCOL="ext:ssh:https"

commit() { git commit --quiet --signoff --author "$AUTHOR" --message "$1"; }

submodule_add() { git submodule add -b master "ext::git --namespace=admins %s $1" "$2"; }

create_dir() {
    echo "Creating dir $1"
    mkdir -p "$1"
    touch "$1/.keep"
    git add "$1/.keep"
    commit "Create $1"
}

migrate() {
    TMP_DIR="tmp"
    mkdir -p "$TMP_DIR"
    src_repo="$TMP_DIR/$1"
    echo "Checking out $1  to $src_repo"
    git clone --quiet "$GIT_URL/$1" "$src_repo"
    cd "$src_repo"
    repo_name=$(git rev-list --max-parents=0 HEAD)
    dst="$DATA_DIR/$repo_name.git"
    git init --bare "../../$dst" --quiet
    git remote add _migrate "../../$dst"
    GIT_ALLOW_PROTOCOL=file GIT_NAMESPACE=admins git push _migrate --mirror
    cd -
    cd "$dst"
    git symbolic-ref refs/namespaces/admins/HEAD  refs/namespaces/admins/refs/heads/master
    git config transfer.hideRefs refs/remotes
    git remote add origin "$GIT_URL/$1"
    cd -
    ln -s "../../$DATA_DIR/$repo_name.git" "$ORGS_DIR/admins/$1.git"
    ln -s "../../$DATA_DIR/$repo_name.git" "$REPOS_DIR/admins/$1.git"
    git add "$ORGS_DIR" "$REPOS_DIR"
    commit "Added repo admins/$1"
    submodule_add "$dst" "$2"
    commit "Installed $1 to $2"
    rm -rf "$TMP_DIR"
}

echo "install" >> .gitignore
git add .gitignore
commit "Add install to .gitignore"
create_dir "$DATA_DIR"
create_dir "$TOKENS_DIR"
create_dir "$REPOS_DIR"
create_dir "$ORGS_DIR"
create_dir "$ORGS_DIR/admins"
create_dir "$REPOS_DIR/admins"
echo "data/*" >> .gitignore
git add .gitignore
commit "Ignore data/ dir contents"

migrate "git-server-tools" "bin"
migrate thinssh "thinssh"

echo "1" > .schema_version
git add .schema_version
commit "Set schema_version to 1"

echo "#!/bin/sh
exec thinssh/bin/thinssh.$(uname -m) \"\$@\"" > git-server
chmod +x git-server
git add git-server
commit "Add git-server script"
if [ ! -f host_key ]; then
    ssh-keygen -t ed25519 -f host_key -N ""
fi
git add host_key
if [ -f host_key.pub ]; then
    git add host_key.pub
fi
commit "Add ssh key"
rm install

#############################################################################
# The above script will setup a git-server on your machine. 
#
# 0. Create an new directory for your server data
# 1. Copy paste this output in an the new directory in a file called "install"
# 2. Make the file "install" executable and execute it
# 3. After execution just start "./git-server"
# 
##############################################################################
# vim: tw=0
'
