#!/bin/sh

set -e
if [ -z "${USER_TOKEN}" ]; then
    echo "No user token provided" >&2; exit 1
fi
ID="$USER_TOKEN"
ORGANIZATION=$1

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
BASEPATH=$(dirname "$SCRIPTPATH")

own_orga() {
    ln -s "../../repos/$ORGANIZATION" "$BASEPATH/data/ids/$ID/$ORGANIZATION"
    echo "Orga $ORGANIZATION is now owned by $ID"
    exit 0
}


mkdir -p "$BASEPATH/data/ids/$ID"
if "$SCRIPTPATH/is-abandoned" "$ORGANIZATION"; then
    own_orga
else
    "$SCRIPTPATH/check-permissions" admin && own_orga
fi
exit 1

# vim: set: ft=SHELL
