#!/bin/sh
set -e
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
BASEPATH=$(dirname "$SCRIPTPATH")
IDSPATH="$BASEPATH/ids"

# shellcheck source=_helper
. "$SCRIPTPATH/_helper"

check=$(find "$IDSPATH" -type d| wc -l)
if [ ! "$check" = "1" ]; then
    exit_err 1 "setup is done"
fi

create_user "$IDSPATH/$USER_TOKEN"
ln -s "../../../orgs/admins" "$IDSPATH/$USER_TOKEN/orgs/admins"
git add "$IDSPATH"
commit "A user joined admins

$USER_TOKEN joined admins"
