#!/bin/sh
set -e
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
BASEPATH=$(dirname "$SCRIPTPATH")
DATAPATH="$BASEPATH/data"
REPOPATH="$DATAPATH/repos"
. "$SCRIPTPATH/_helper"

update_submodule(){
    cd "$BASEPATH" || (echo "Couldn't cd in $BASEPATH" >&2 && exit 2)
    git submodule update --remote --force "$1"
    git add "$1"
    if  ! commit "Update submodules $1"; then
        echo submodule "$1" did not change >&2
    fi
}

if "$SCRIPTPATH/check-permissions" admin; then
    cd "$REPOPATH/admin/git-server-tools.git"
    git fetch --force --quiet origin master:master
    update_submodule bin || echo "Submodule bin did not change" >&2
    cd "$REPOPATH/admin/thinssh.git"
    git fetch --force --quiet origin master:master
    update_submodule thinssh || echo "Submodule thinssh did not change" >&2
else
    echo "permission denied" >&2
    exit 2
fi


