#!/bin/sh
set -e
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
BASEPATH=$(dirname "$SCRIPTPATH")

if "$SCRIPTPATH/check-permissions" admin; then
    "$BASEPATH/update"
else
    echo "Not allowed" >&2
fi


